/**
 * The DEFAULT backend: a committed USDA FoodData Central extract, searched
 * entirely in-process.
 *
 * WHY THIS ONE IS THE DEFAULT. A self-hoster must get working macros with no API
 * key, no account, and no outbound request to anyone — including us (spec 04,
 * OPEN TASK). USDA FDC is a work of the US federal government, so it is public
 * domain and we may redistribute it outright; OpenFoodFacts (ODbL share-alike)
 * and LCC (BLS forbids redistribution) cannot be shipped and are therefore
 * remote-only connectors. `describe().requiresNetwork` is `false` here and `true`
 * for both of those, which is the whole licensing story in one boolean.
 *
 * The artifact is generated by `scripts/food-data/build-fdc-dataset.ts` (8 041
 * rows, ~1.8 MB) and read once at boot. A FULL LINEAR SCAN per query is
 * deliberate: 8 k prepared rows score in ~8 ms, which is nothing next to a
 * 25–110 s vision call, and an inverted index would be a second structure to keep
 * in step with the dataset for no measurable gain at this size.
 *
 * GERMAN WITHOUT A LOCALE PARAMETER. openplate ships en + de, but the
 * chat-completions request carries an image and nothing else — there is no locale
 * on the wire to branch on. So the alias pass is OPPORTUNISTIC: if any token of
 * the query appears in `data/de-food-aliases.json`, the translated query is scored
 * as WELL as the original and each row keeps its better score. That costs a second
 * scan on German input only, cannot lose an English match (the original is always
 * scored), and needs no protocol change. Where a word exists in both languages
 * with different meanings — "paprika" is a spice in English and a bell pepper in
 * German — both readings compete on their merits instead of one being silently
 * discarded.
 */
import { readFileSync } from 'node:fs';
import { z } from 'zod';
import type { Macros } from '../contract/plate-identification.js';
import type { JsonValue } from '../json.js';
import { prepareDocument, prepareQuery, scorePrepared, tokenize, type LexicalDocument } from './lexical.js';
import type {
  FoodCandidate,
  FoodSource,
  FoodSourceDescription,
  SearchOptions,
} from './types.js';

/** Default candidate count when a caller does not ask for one. */
const DEFAULT_LIMIT = 24;

/**
 * Nothing below this can be the right answer, so it is dropped before ranking.
 * Purely a size guard on the returned array — the ACCEPT threshold that decides
 * whether a macro reaches a user lives in `search-foods.ts` and is much higher.
 */
const MIN_RETURNED_SCORE = 0.2;

const MacroRowSchema = z.object({
  carbs: z.number().nullable(),
  fiber: z.number().nullable(),
  sugars: z.number().nullable(),
  polyols: z.number().nullable(),
  protein: z.number().nullable(),
  fat: z.number().nullable(),
  kcal: z.number().nullable(),
});

const FdcFoodSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(1),
  category: z.string().nullable(),
  macrosPer100g: MacroRowSchema,
});

/**
 * The dataset contract. `_meta` is validated loosely on purpose — it is
 * provenance for a human reader (row count, release dates, source URLs) and a
 * stricter schema here would turn a documentation improvement in the generator
 * into a boot failure.
 */
const FdcDatasetSchema = z.object({
  _meta: z
    .object({
      generatedAt: z.string().optional(),
      rowCount: z.number().optional(),
      license: z.string().optional(),
      attribution: z.string().nullable().optional(),
    })
    .loose()
    .optional(),
  foods: z.array(FdcFoodSchema),
});

const AliasFileSchema = z.object({
  aliases: z.record(z.string(), z.string()),
});

interface PreparedFood {
  id: string;
  name: string;
  category: string | null;
  macrosPer100g: Macros;
  document: LexicalDocument;
}

export interface FdcFoodSourceOptions {
  datasetPath: string;
  /** Path to `data/de-food-aliases.json`. Omitted ⇒ no alias pass (English only). */
  aliasPath?: string;
}

export class FdcDatasetError extends Error {}

function readJsonFile(path: string, what: string): JsonValue {
  let raw: string;
  try {
    raw = readFileSync(path, 'utf8');
  } catch (error) {
    throw new FdcDatasetError(
      `Could not read the ${what} at ${path}: ${error instanceof Error ? error.message : 'unknown error'}`,
    );
  }
  try {
    // SAFETY: `JSON.parse` is typed `any` and produces exactly `JsonValue`. Both
    // callers run a Zod schema over the result before reading a field.
    return JSON.parse(raw) as JsonValue;
  } catch {
    throw new FdcDatasetError(`The ${what} at ${path} is not valid JSON.`);
  }
}

/** Whole-string first, then token-wise. Returns `null` when nothing was translated. */
export function translateAliases(query: string, aliases: ReadonlyMap<string, string>): string | null {
  const whole = aliases.get(query.trim().toLowerCase());
  if (whole !== undefined) return whole;

  const tokens = tokenize(query);
  if (tokens.length === 0) return null;
  let changed = false;
  const translated = tokens.map((token) => {
    const alias = aliases.get(token);
    if (alias === undefined) return token;
    changed = true;
    return alias;
  });
  return changed ? translated.join(' ') : null;
}

/**
 * Reads and prepares the dataset. Throws `FdcDatasetError` on anything wrong —
 * the factory in `index.ts` turns that into a loud warning and a disabled
 * resolver, because a missing food dataset must not stop the service from
 * identifying plates.
 */
export function createFdcFoodSource(options: FdcFoodSourceOptions): FoodSource {
  const parsed = FdcDatasetSchema.safeParse(readJsonFile(options.datasetPath, 'FDC dataset'));
  if (!parsed.success) {
    throw new FdcDatasetError(
      `The FDC dataset at ${options.datasetPath} does not match the expected shape. ` +
        `Regenerate it with \`pnpm food-data:fdc\`.`,
    );
  }
  if (parsed.data.foods.length === 0) {
    throw new FdcDatasetError(`The FDC dataset at ${options.datasetPath} contains no foods.`);
  }

  const foods: PreparedFood[] = parsed.data.foods.map((food) => ({
    id: food.id,
    name: food.name,
    category: food.category,
    macrosPer100g: food.macrosPer100g,
    document: prepareDocument(food.name),
  }));
  const byId = new Map(foods.map((food) => [food.id, food]));

  const aliases = new Map<string, string>();
  if (options.aliasPath) {
    const aliasFile = AliasFileSchema.safeParse(readJsonFile(options.aliasPath, 'German alias table'));
    if (!aliasFile.success) {
      throw new FdcDatasetError(`The German alias table at ${options.aliasPath} is malformed.`);
    }
    for (const [german, english] of Object.entries(aliasFile.data.aliases)) {
      aliases.set(german.toLowerCase(), english.toLowerCase());
    }
  }

  /**
   * USDA FDC is CC0. `attribution` is `null` and that is a licence FACT, not an
   * omission — see the LCC connector for the case where it is an obligation.
   */
  const description: FoodSourceDescription = {
    name: 'fdc',
    license: 'CC0 / public domain (USDA FoodData Central — a work of the U.S. federal government)',
    attribution: null,
    requiresNetwork: false,
  };

  function toCandidate(food: PreparedFood, score: number, lexical: number): FoodCandidate {
    return {
      id: food.id,
      name: food.name,
      category: food.category,
      // Passed through verbatim. A null here came from USDA publishing no value.
      macrosPer100g: food.macrosPer100g,
      attribution: description.attribution,
      score,
      signals: { lexical, embedding: null },
    };
  }

  return {
    describe: () => description,

    async search(query: string, searchOptions: SearchOptions = {}): Promise<FoodCandidate[]> {
      const limit = searchOptions.limit ?? DEFAULT_LIMIT;
      const prepared = [prepareQuery(query)];

      // Skipped when the caller states an English query — see the module header
      // for why the default is to try the alias pass regardless of locale.
      const wantsAliasPass = !searchOptions.locale?.toLowerCase().startsWith('en');
      if (wantsAliasPass && aliases.size > 0) {
        const translated = translateAliases(query, aliases);
        if (translated) prepared.push(prepareQuery(translated));
      }

      const scored: FoodCandidate[] = [];
      for (const food of foods) {
        let best = 0;
        for (const preparedQuery of prepared) {
          const score = scorePrepared(preparedQuery, food.document).score;
          if (score > best) best = score;
        }
        if (best < MIN_RETURNED_SCORE) continue;
        scored.push(toCandidate(food, best, best));
      }

      scored.sort((a, b) => b.score - a.score);
      return scored.slice(0, limit);
    },

    async getById(id: string): Promise<FoodCandidate | null> {
      const food = byId.get(id);
      if (!food) return null;
      // An explicit id lookup is not a similarity question — the caller already
      // chose this row, so it scores 1 rather than being re-ranked against a
      // query it was not given.
      return toCandidate(food, 1, 1);
    },
  };
}
